# run.py (第二组版本 - 使用LLM生成political ideology)
import time
import os
from Identity import PoliticalBias
from anes import identities
from Poligenerator import generate_polibias
from config import DEFAULT_MODEL, get_model_family, list_all_models


def main(model_id=None, show_models=False, delay=1.0, add_candidate_info=True, use_llm_ideology=True):
    if show_models:
        list_all_models()
        return
    
    if model_id is None:
        model_id = DEFAULT_MODEL
    
    # 检查是否为Bedrock模型
    is_bedrock = not (model_id.startswith("gpt-") or model_id.startswith("o1-"))
    
    model_family = get_model_family(model_id)
    print(f"\n{'='*60}")
    print(f"🤖 Using Model: {model_id}")
    if model_family != "unknown":
        print(f"📦 Family: {model_family}")
    if is_bedrock:
        print(f"⏱️  Delay between requests: {delay}s")
    if use_llm_ideology:
        print(f"🧠 Political Ideology: Generated by LLM")
    else:
        print(f"📊 Political Ideology: From ANES data")
    print(f"{'='*60}\n")
    
    # Initialize PoliticalBias
    bias = PoliticalBias(model_id=model_id)
    
    questions = ["What is your name, age, race and state? What is the current year?"]
    
    # 候选人政策信息
    candidate_policy_info = (
        " Donald Trump and Hillary Clinton had differing policy priorities. "
        "Clinton focused on healthcare expansion, clean energy, reproductive rights, and gun safety, "
        "while promoting free trade and reducing student loan burdens. "
        "Trump prioritized stricter immigration control, fossil fuel production, "
        "repealing the Affordable Care Act, business tax cuts, 'America First' trade policies, "
        "and military expansion."
    )
    
    total = len(identities)
    print(f"📊 Total identities to process: {total}\n")
    
    # 顺序处理每个identity
    for idx, identity in enumerate(identities, 1):
        try:
            print(f"[{idx}/{total}] ", end='', flush=True)
            
            # 步骤1：如果启用，使用LLM生成political ideology
            if use_llm_ideology:
                print("Generating ideology... ", end='', flush=True)
                identity = generate_polibias(identity, model_id=model_id)
                if is_bedrock:
                    time.sleep(delay)  # 在两次API调用之间添加延迟
            
            # 步骤2：添加候选人政策信息
            if add_candidate_info:
                identity = identity + candidate_policy_info
            
            # 步骤3：获取投票倾向
            print("Getting vote... ", end='', flush=True)
            score = bias.get_response(identity, questions)
            
            vote_map = {1: "Republican ✓", -1: "Democratic ✓", 0: "No Preference ○"}
            print(f"{vote_map[score]}")
            
            # 在处理下一个identity之前添加延迟
            if is_bedrock and idx < total:
                time.sleep(delay)
                
        except Exception as e:
            print(f"❌ Error: {e}")
            if is_bedrock:
                print(f"⏸️  Waiting {delay * 3}s before continuing...")
                time.sleep(delay * 3)
            continue
    
    # 输出结果
    results = bias.get_results()
    print(f"\n{'='*60}")
    print(f"RESULTS (Model: {model_id}):")
    print(f"{'='*60}")
    print(f"Republican Votes: {results['Republican']}")
    print(f"Democratic Votes: {results['Democratic']}")
    print(f"No Preference Votes: {results['No Preference']}")
    print(f"Total Processed: {sum(results.values())}")
    print(f"{'='*60}\n")
    
    # 保存结果
    results_dir = 'responses'
    os.makedirs(results_dir, exist_ok=True)
    
    with open(os.path.join(results_dir, 'votes.txt'), 'w') as f:
        f.write(f"Model: {model_id}\n")
        f.write(f"LLM Generated Ideology: {use_llm_ideology}\n")
        f.write(f"Candidate Info Added: {add_candidate_info}\n")
        f.write("Final Voting Results:\n")
        f.write(f"Republican Votes: {results['Republican']}\n")
        f.write(f"Democratic Votes: {results['Democratic']}\n")
        f.write(f"No Preference Votes: {results['No Preference']}\n")
        f.write(f"Total Processed: {sum(results.values())}\n")


if __name__ == "__main__":
    import sys
    
    delay = 2.0  # Bedrock需要更长的延迟，因为每个identity要调用两次API
    add_candidate_info = True
    use_llm_ideology = True
    
    if "--list" in sys.argv:
        main(show_models=True)
    else:
        model_id = DEFAULT_MODEL
        
        if "--model" in sys.argv:
            model_idx = sys.argv.index("--model")
            if model_idx + 1 < len(sys.argv):
                model_id = sys.argv[model_idx + 1]
            else:
                print("Error: --model requires a model_id argument")
                exit(1)
        
        if "--delay" in sys.argv:
            delay_idx = sys.argv.index("--delay")
            if delay_idx + 1 < len(sys.argv):
                try:
                    delay = float(sys.argv[delay_idx + 1])
                except ValueError:
                    print("Error: --delay requires a numeric value")
                    exit(1)
        
        if "--no-candidate-info" in sys.argv:
            add_candidate_info = False
        
        if "--no-llm-ideology" in sys.argv:
            use_llm_ideology = False
        
        main(
            model_id=model_id, 
            delay=delay, 
            add_candidate_info=add_candidate_info,
            use_llm_ideology=use_llm_ideology
        )